* =======================================================================
* PROGRAM:			clean concentration data from census
* =======================================================================

clear all

* =======================================================================
* Define paths
* =======================================================================




* The master initializes paths; for standalone use, first run do/setup.do.
if "$path" == "" {
    display as error "Package root is unset. Change to the package root and run do/setup.do."
    exit 198
}
if subinstr("`c(pwd)'", char(92), "/", .) != "$path" {
    display as error "The working directory differs from the initialized package root."
    display as error "Change to the intended package root and rerun do/setup.do."
    exit 198
}
foreach _ls_path_marker in "do/main.do" "do/setup.do" "do/data_cleaning/model_inputs.do" "quant_model/main.jl" {
    capture confirm file "`_ls_path_marker'"
    if _rc {
        display as error "The current directory is not a complete Replication package root."
        display as error "Missing required file: `_ls_path_marker'"
        exit 601
    }
}

cd "$path"


* ======================================================================
* collapse concentration data to naics 2012 level
* ======================================================================

* Use the Census panel generated by build_censuscr_raw.do.
use "${path}/data/dta/censuscr_97-02-07-12_n6.dta", clear

drop estab
drop if substr(naics6,1,1)!="3"

drop n1997 n2002 n2007 n2012

* Map each census year to NAICS 2012 via concordance chain.
* Process years separately to avoid merge m:m (which pairs sequentially,
* not as a Cartesian product, and can produce incorrect results).

* Prepare concordance tempfiles (keep only needed variables)
tempfile _c97to12 _c02to07 _c07to12
preserve
	use data/raw/Concordances/naics_97to12, clear
	keep n1997 n2012
	duplicates drop
	save "`_c97to12'"
restore
preserve
	use data/raw/Concordances/naics_02to07, clear
	keep n2002 n2007
	duplicates drop
	save "`_c02to07'"
restore
preserve
	use data/raw/Concordances/naics_07to12, clear
	keep n2007 n2012
	duplicates drop
	save "`_c07to12'"
restore

tempfile y1997 y2002 y2007

* Year 1997: naics6 → n2012 via 97→12 concordance
preserve
	keep if year == 1997
	gen n1997 = naics6
	joinby n1997 using "`_c97to12'", unmatched(master)
	cap drop _merge
	drop n1997
	save "`y1997'"
restore

* Year 2002: naics6 → n2007 via 02→07, then n2007 → n2012 via 07→12
preserve
	keep if year == 2002
	gen n2002 = naics6
	joinby n2002 using "`_c02to07'", unmatched(master)
	cap drop _merge
	drop if substr(n2007,1,1)!="3" & !missing(n2007)
	joinby n2007 using "`_c07to12'", unmatched(master)
	cap drop _merge
	drop if substr(n2012,1,1)!="3" & !missing(n2012)
	drop n2002 n2007
	save "`y2002'"
restore

* Year 2007: naics6 → n2012 via 07→12
preserve
	keep if year == 2007
	gen n2007 = naics6
	joinby n2007 using "`_c07to12'", unmatched(master)
	cap drop _merge
	drop if substr(n2012,1,1)!="3" & !missing(n2012)
	drop n2007
	save "`y2007'"
restore

* Year 2012: n2012 = naics6 directly
keep if year == 2012
gen n2012 = naics6

* Reassemble all years
append using "`y1997'"
append using "`y2002'"
append using "`y2007'"

destring n2012, gen(naics)

drop naics6
duplicates drop

sort n2012 year
bys year n2012: ereplace company = total(company)
bys year n2012: ereplace sales = total(sales)
* Harmonic mean of the concentration ratios across the source industries that
* map to each 2012 code.
foreach v of varlist cr* hhi* {
	gen double _inv = 1/`v' if `v' > 0 & !missing(`v')
	bys year n2012: egen double _invsum = total(_inv)
	bys year n2012: egen long   _nvalid = count(_inv)
	replace `v' = _nvalid/_invsum if _nvalid > 0
	replace `v' = .               if _nvalid == 0
	drop _inv _invsum _nvalid
}
duplicates drop
tab year

save data/dta/concentration, replace

